sudo: required
services:
  - mysql
before_install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse"
  - sudo apt-get update
  - sudo apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" gcc g++ make zip unzip apache2 apache2-utils bsdmainutils libcurl4-gnutls-dev libjsoncpp-dev libmagic-dev autoconf automake sudo debootstrap procps gcc g++ openjdk-7-jre-headless openjdk-7-jdk ghc fp-compiler libcgroup-dev devscripts shellcheck
jdk:
  - openjdk7

language: php
php:
  - '7.1'
script: ./travis.sh
dist: trusty
