# Note: this docker compose stack should only be used for development purposes.
# Do not use it for production deployments. If you want to deploy DOMjudge in
# production with Docker, see https://hub.docker.com/r/domjudge/domserver.

version: '3'

services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=domjudge
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=domjudge
      - MYSQL_DATABASE=domjudge
    ports:
      # Useful to connect a local MySQL client / GUI
      - 127.0.0.1:13306:3306
    command: --max-connections=1000 --max-allowed-packet=512M
    volumes:
      - /var/lib/mysql
  domjudge:
    image: domjudge/domjudge-contributor
    hostname: domjudge-contributor
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - .:/domjudge:cached
      - /chroot
    links:
      - mariadb:mariadb
    ports:
      - 12345:80
    privileged: true
