when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false

    framework:
        profiler:
            only_exceptions: false
            collect_serializer_data: true

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler:
            # Do not collect profiling information, since we don't need it
            collect: false
            # But do collect serializer data, since it's deprecated to not set it to true
            collect_serializer_data: true
