# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    role_hierarchy:
        ROLE_JURY: [ROLE_BALLOON, ROLE_API]
        ROLE_ADMIN: [ROLE_JURY, ROLE_API]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    encoders:
        DOMJudgeBundle\Entity\User:
            algorithm: bcrypt
    providers:
        domjudge_db_provider:
          entity:
            class: DOMJudgeBundle:User
            property: username


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # api only does http_basic auth
        api:
            pattern: ^/api
            provider: domjudge_db_provider
            http_basic: ~
            stateless: true
            user_checker: domjudge.user_checker
            anonymous: ~

        # api only does http_basic auth
        feed:
            pattern: ^/feed
            provider: domjudge_db_provider
            http_basic: ~
            user_checker: domjudge.user_checker
            stateless: true
            anonymous: ~

        # rest of app does form_login
        main:
            pattern: ^/
            provider: domjudge_db_provider
            user_checker: domjudge.user_checker

            anonymous: ~
            form_login:
              login_path: login
              check_path: login
              csrf_token_generator: security.csrf.token_manager
              use_referer: true
              default_target_path: legacy.index
              always_use_default_target_path: true

            logout:
                path:   logout
                target: /public

    access_control:
      - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/index.php$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/public, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/jury-v2, roles: ROLE_ADMIN }
      - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
