# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    LegacyBundle\Controller\:
        resource: '../../src/LegacyBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    DOMJudgeBundle\:
        resource: '../../src/DOMJudgeBundle/*'
        exclude: '../../src/DOMJudgeBundle/{Entity,Repository,Tests}'

    DOMJudgeBundle\Controller\API\JudgementTypeController:
        arguments:
            $rootDir: '%kernel.root_dir%'

    DOMJudgeBundle\Serializer\:
        resource: '../../src/DOMJudgeBundle/Serializer/*'
        tags:
        -   name: jms_serializer.event_subscriber

    DOMJudgeBundle\ApiDescriber\ParameterRefMergeDescriber:
        tags:
        -   name: nelmio_api_doc.describer
            priority: -999

    LegacyBundle\Controller\FallbackController:
        arguments:
            $webDir: "%kernel.root_dir%/../../www"

    DOMJudgeBundle\Validator\Constraints\UserRegistrationValidator:
        tags:
        -   name: validator.constraint_validator

    DOMJudgeBundle\EventListener\ApiHeadersListener:
        tags:
        -   name: kernel.event_listener
            event: kernel.response
            method: onKernelResponse
